version: "3"
volumes:
  postgres-data:
    driver: local
  dispatcher-redis-data:
    driver: local

services:
  dispatcher_redis:
    image: redis
    volumes:
      - dispatcher-redis-data:/var/lib/redis
    command: redis-server --appendonly yes

  service_core_db:
    image: library/postgres:9.6.5-alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: service_core

  # service just for apply migrations or seed
  migrations:
    build:
      context: ./
      dockerfile: Dockerfile
    # image: comum/services-core:latest
    env_file:
      - ./compose_env/.service_core_migrator.env
    command: ["./scripts/run_migrations.sh"]
    volumes: 
      - ./migrations:/usr/app/migrations
    links:
        - "service_core_db:service_core_db"

  payment_processor_dispatcher:
    build:
      context: ../payment-service-api
      dockerfile: Dockerfile
    # image: comum/payment-service:latest
    env_file:
      - ./compose_env/.payment_processor_dispatcher.env
    command: ["./dispatchers/payment_processor_dispatcher"]
    links:
      - "service_core_db:service_core_db"
      - "dispatcher_redis:dispatcher_redis"
    depends_on:
      - service_core_db
      - dispatcher_redis

  subscriptions_scheduler:
    build:
      context: ../payment-service-api
      dockerfile: Dockerfile
    env_file:
      - ./compose_env/.subscriptions_scheduler.env
    command: ["./scripts/subscription_scheduler.js"]
    links:
      - "service_core_db:service_core_db"
    depends_on:
      - service_core_db

  payment_service_api:
    image: postgrest/postgrest:v0.4.3.0
    env_file:
      - ./compose_env/.payment_service_api.env
    depends_on:
      - service_core_db
    links:
      - "service_core_db:service_core_db"
    ports:
      - "3001:3000"

  project_service_api:
    image: postgrest/postgrest:v0.4.3.0
    env_file:
      - ./compose_env/.project_service_api.env
    depends_on:
      - service_core_db
    links:
      - "service_core_db:service_core_db"
    ports:
      - "3002:3000"

  community_service_api:
    image: postgrest/postgrest:v0.4.3.0
    env_file:
      - ./compose_env/.community_service_api.env
    depends_on:
      - service_core_db
    links:
      - "service_core_db:service_core_db"
    ports:
      - "3003:3000"

  platform_service_api:
    image: postgrest/postgrest:v0.4.3.0
    env_file:
      - ./compose_env/.platform_service_api.env
    depends_on:
      - service_core_db
    links:
      - "service_core_db:service_core_db"
    ports:
      - "3004:3000"

  analytics_service_api:
    image: postgrest/postgrest:v0.4.3.0
    env_file:
      - ./compose_env/.analytics_service_api.env
    depends_on:
      - service_core_db
    links:
      - "service_core_db:service_core_db"
    ports:
      - "3005:3000"
