version: "3"
volumes:
  postgres-data:
    driver: local
  dispatcher-redis-data:
    driver: local

services:
  dispatcher_redis:
    image: redis
    volumes:
      - dispatcher-redis-data:/var/lib/redis
    command: redis-server --appendonly yes

  service_core_db:
    image: library/postgres:9.6.5-alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    environment:
      POSTGRES_PASSWORD: 'example'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'service_core'

  payment_processor_dispatcher:
    image: comum/payment-service:latest
    environment:
      PROCESS_PAYMENT_DATABASE_URL: postgres://postgres:example@service_core_db:5432/service_core
    command: ["pg-dispatcher", "--db-uri", "postgres://postgres:example@service_core_db:5432/service_core", "--redis-uri", "redis://dispatcher_redis:6379", "--channel", "process_payments_channel", "--workers", "2", "--exec", "node ./scripts/process_payment.js"]
    links:
      - "service_core_db:service_core_db"
      - "dispatcher_redis:dispatcher_redis"
    depends_on:
      - service_core_db
      - dispatcher_redis


  payment_service_api:
    image: postgrest/postgrest:v0.4.3.0
    environment:
      DATABASE_URL: postgres://postgres:example@service_core_db:5432/service_core
      PROCESS_PAYMENT_DATABASE_URL: postgres://postgres:example@service_core_db:5432/service_core
      PGRST_DB_ANON_ROLE: anonymous
      PGRST_DB_POOL: 10
      PGRST_DB_SCHEMA: payment_service_api
      PGRST_DB_URI: postgres://postgrest:example@service_core_db:5432/service_core
      PGRST_JWT_SECRET: bUH75katNm6Yj0iPSchcgUuTwYAzZr7C
      PGRST_SERVER_PROXY_URI: https://0.0.0.0:3000/
      POSTGREST_VER: 0.4.3.0
      PGRST_SERVER_PORT: 3000
      PGRST_SERVER_HOST: 0.0.0.0
    depends_on:
      - service_core_db
    links:
      - "service_core_db:service_core_db"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: "50M"
        restart_policy:
          condition: on-failure
    ports:
      - "3001:3000"

  project_service_api:
    image: postgrest/postgrest:v0.4.3.0
    environment:
      DATABASE_URL: postgres://postgres:example@service_core_db:5432/service_core
      PROCESS_PAYMENT_DATABASE_URL: postgres://postgres:example@service_core_db:5432/service_core
      PGRST_DB_ANON_ROLE: anonymous
      PGRST_DB_POOL: 10
      PGRST_DB_SCHEMA: project_service_api
      PGRST_DB_URI: postgres://postgrest:example@service_core_db:5432/service_core
      PGRST_JWT_SECRET: bUH75katNm6Yj0iPSchcgUuTwYAzZr7C
      PGRST_SERVER_PROXY_URI: https://0.0.0.0:3000/
      POSTGREST_VER: 0.4.3.0
      PGRST_SERVER_PORT: 3000
      PGRST_SERVER_HOST: 0.0.0.0
    depends_on:
      - service_core_db
    links:
      - "service_core_db:service_core_db"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: "50M"
        restart_policy:
          condition: on-failure
    ports:
      - "3002:3000"

  community_service_api:
    image: postgrest/postgrest:v0.4.3.0
    environment:
      DATABASE_URL: postgres://postgres:example@service_core_db:5432/service_core
      PROCESS_PAYMENT_DATABASE_URL: postgres://postgres:example@service_core_db:5432/service_core
      PGRST_DB_ANON_ROLE: anonymous
      PGRST_DB_POOL: 10
      PGRST_DB_SCHEMA: community_service_api
      PGRST_DB_URI: postgres://postgrest:example@service_core_db:5432/service_core
      PGRST_JWT_SECRET: bUH75katNm6Yj0iPSchcgUuTwYAzZr7C
      PGRST_SERVER_PROXY_URI: https://0.0.0.0:3000/
      POSTGREST_VER: 0.4.3.0
      PGRST_SERVER_PORT: 3000
      PGRST_SERVER_HOST: 0.0.0.0
    depends_on:
      - service_core_db
    links:
      - "service_core_db:service_core_db"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: "50M"
        restart_policy:
          condition: on-failure
    ports:
      - "3003:3000"

  platform_service_api:
    image: postgrest/postgrest:v0.4.3.0
    environment:
      DATABASE_URL: postgres://postgres:example@service_core_db:5432/service_core
      PROCESS_PAYMENT_DATABASE_URL: postgres://postgres:example@service_core_db:5432/service_core
      PGRST_DB_ANON_ROLE: anonymous
      PGRST_DB_POOL: 10
      PGRST_DB_SCHEMA: platform_service_api
      PGRST_DB_URI: postgres://postgrest:example@service_core_db:5432/service_core
      PGRST_JWT_SECRET: bUH75katNm6Yj0iPSchcgUuTwYAzZr7C
      PGRST_SERVER_PROXY_URI: https://0.0.0.0:3000/
      POSTGREST_VER: 0.4.3.0
      PGRST_SERVER_PORT: 3000
      PGRST_SERVER_HOST: 0.0.0.0
    depends_on:
      - service_core_db
    links:
      - "service_core_db:service_core_db"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: "50M"
        restart_policy:
          condition: on-failure
    ports:
      - "3004:3000"
