version: 2
jobs:
  build:
    docker:
      - image: comum/docker-build-env:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: docker run -e POSTGRES_DB=services_core_test --name pg_default -p 5432:5432 -d postgres:9.6
      - run: docker build -f Dockerfile.test -t comum/services-core:test .
      - run: apk add --update ca-certificates openssl && update-ca-certificates

      - run: docker run -i --rm --link pg_default:pg_default comum/services-core:test psql -U postgres -h pg_default -p 5432 services_core_test < init.sql
      - run: docker run -i --rm --link pg_default:pg_default comum/services-core:test psql -U postgres -h pg_default -p 5432 -c "alter user postgrest with superuser;"
      - run: docker run -i --rm --link pg_default:pg_default -e="DATABASE_URL=postgres://postgres@pg_default:5432/services_core_test" comum/services-core:test ./scripts/run_migrations.sh
      - run: docker run -i --rm --link pg_default:localhost -e "TEST_DB_HOST=localhost" -e="DB_NAME=services_core_test" -e "TEST_DB_USER=postgres" -e "TEST_DB_PORT=5432" comum/services-core:test bash -c './scripts/generate_dump_test_schema.sh && ./scripts/run_tests.sh'
  push_docker:
    docker:
      - image: comum/docker-build-env:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      # with credentials stored in the UI
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      # build the application container
      - run: docker build -t comum/services-core:latest .
      # deploy the container
      - run: docker push comum/services-core:latest
  deploy_sandbox:
    docker:
      - image: comum/docker-build-env:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: apk update && apk add nodejs nodejs-npm bash
      - run: npm install -g heroku-cli
      - run: bash .circleci/setup-heroku.sh
      - run: heroku container:login

      - run: heroku container:push service_core --recursive -a services-core-db
      - run: heroku run ./scripts/run_migrations.sh -a services-core-db --type=service_core

      - run: heroku restart -a public-analytics-service-api
      - run: heroku restart -a community-service-api
      - run: heroku restart -a payment-service-api
      - run: heroku restart -a project-service-api
      - run: heroku restart -a platform-service-api


workflows:
  version: 2
  build-and-push:
    jobs:
      - build
      - push_docker:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy_sandbox:
          requires:
            - build
          filters:
            branches:
              only: master
