version: 2
jobs:
  build:
    docker:
      - image: comum/docker-build-env:latest
    branches:
      only:
        - master
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      # with credentials stored in the UI
      - run: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      # build the application container
      - run: docker build -t comum/payment-service:latest .
      # deploy the container
      - run: docker push comum/payment-service:latest
  deploy_sandbox:
    docker:
      - image: comum/docker-build-env:latest
    branches:
      only:
        - master
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: apk update && apk add nodejs nodejs-npm bash
      - run: npm install -g heroku-cli
      - run: docker build -t comum/payment-service:latest .
      - run: bash .circleci/setup-heroku.sh
      - run: heroku container:login
      - run: heroku container:push payment_disptacher --recursive -a payment-dispatcher
      - run: heroku container:push subsription_scheduler --recursive -a subscription-scheduler

