version: 2
jobs:
  build:
    docker:
      - image: comum/docker-build-env:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: ./test.sh

  deploy_sandbox:
    docker:
      - image: comum/docker-build-env:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: apk update && apk add git nodejs nodejs-npm bash
      - run: npm install -g heroku
      - run: bash .circleci/setup-heroku.sh
      - run: heroku container:login

      - run: heroku container:push web --recursive -a $PRODUCTION_PROXY_APP
      - run: heroku container:release web -a $PRODUCTION_PROXY_APP

  deploy_sandbox:
    docker:
      - image: comum/docker-build-env:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: apk update && apk add git nodejs nodejs-npm bash
      - run: npm install -g heroku
      - run: bash .circleci/setup-heroku.sh
      - run: heroku container:login

      - run: heroku container:push web --recursive -a $SANDBOX_PROXY_APP
      - run: heroku container:release web -a $SANDBOX_PROXY_APP

workflows:
  version: 2
  build-and-push:
    jobs:
      - build
      - deploy_sandbox:
          requires:
            - build
          filters:
            branches:
              only: develop
      - deploy_production:
          requires:
            - build
          filters:
            branches:
              only: master


